### PR TITLE
Add day 1

### PR DESCRIPTION
**Pull request by Lito-Frito**
I pray I did this right

### CODE REVIEW

**Comment by dmadisetti** [comment]
Woops, nope, because this will just count as another commit.

Only the extra days you want to add should be new commits.

But you are trying to add day 5 and 6 right? You are at 4 commits now, so just add another commit to this PR (just 1!) with all the files you want and I'll merge it (no rebasing!)

**Comment by dmadisetti** [comment]
If you do have to make changes that shouldn't be tracked, you can commit `DNT:` in the commit message (which stands for don not track)

**Comment by Lito-Frito** [comment]
> Woops, nope, because this will just count as another commit.
> 
> Only the extra days you want to add should be new commits.
> 
> But you are trying to add day 5 and 6 right? You are at 4 commits now, so just add another commit to this PR (just 1!) with all the files you want and I'll merge it (no rebasing!)

Ah understood. So basically, when I recreated this repo, I should just add a commit so that Day 5 counts. Then add another commit so Day 6 counts, correct?

**Comment by dmadisetti** [comment]
Pull requests do not count! So I think we're good

**Comment by Lito-Frito** [comment]
> Pull requests do not count! So I think we're good

Success!

**Pull request merged**
