### PR TITLE
Los

### PR DESCRIPTION
**Pull request by Lito-Frito**
Add day 4

### CODE REVIEW

**Comment by dmadisetti** [comment]
Hmm. Can you rebase the branch on your end? For some reason it doesn't want to rebase and merge, which is how we ensure you get your count

**Comment by Lito-Frito** [comment]
I think I did rebase but it still didn't work? I ran `git fetch`, then `git rebase origin/Los`.  But it said it everything was up-to-date/there was nothing to do. Tbh, git is one of my weakest areas since I haven't collaborated with people much before. If you have any tutorials or something to recommend, I can check em out and try to troubleshoot on my own

**Comment by dmadisetti** [comment]
Yeah! This set of puzzles helped me get the deeper idea of git: https://learngitbranching.js.org/

It walks you through pretty slowly. Would definitely count as a coding day!

**Comment by Lito-Frito** [comment]
> Yeah! This set of puzzles helped me get the deeper idea of git: https://learngitbranching.js.org/
> 
> It walks you through pretty slowly. Would definitely count as a coding day!

Good looks! This is a pretty fun tool and I'm def learning a lot. I'll try to work things through on my end and I'll keep you posted if I absolutely can't for some reason

**Comment by Lito-Frito** [comment]
Ok, I got to the part in the tutorials about rebasing and I think I successfully did what I needed to on my end. Mind trying again and letting me know if it didn't work again?

**Comment by dmadisetti** [comment]
Hmm. I think you will have force push to get it to work.

Sync your head with BBT, and then add your commits. If it still doesn't work, I'll try a squash commit, but you might not get the credit?

**Comment by Lito-Frito** [comment]
Ok, I think I actually did it right for real this time. I think I understood by what you meant by rebasing. So I rebased a copy of bbt's main branch into my branch called Los. And now that should make merging my PR ok, right? At least from what I've seen in the tutorial (based on what they said about pointers/commits)

**Comment by dmadisetti** [comment]
You might have to track the BBT remote.

So you'd do

`git add remote bbt https://github.com/baltimoreblacktechies/100daysOfCode-2022.git`

`git fetch bbt`

`git checkout bbt/main`

and rebase from there?

We should def make the process simpler though

**Comment by dmadisetti** [comment]
Lol, I can just squash this though, unless it's a challenge now

**Comment by Lito-Frito** [comment]
> Lol, I can just squash this though, unless it's a challenge now

No, sorry! Yesterday was super busy and just got away from me. I'll try today and see what happens and keep you posted

**Comment by Lito-Frito** [comment]
Ok, I think I got it to work this time. I rebased, created a new branch from that and then merged that branch into Los. I think that should work

**Comment by dmadisetti** [comment]
Nottt exactly Carlos. A good way to check what is going on is to look at the network diagram: https://github.com/baltimoreblacktechies/100daysOfCode-2022/network

You have certainly made it colourful! 

Another good way to check the network disagram is with:

`log --graph --pretty=format:"%C(auto)%h%<(3)%d %s %C(bold blue)(%cr, %an)%Creset" --abbrev-commit --all`

in my .gitconfig I have `alias.l=log --graph --pretty=format:"%C(auto)%h%<(3)%d %s %C(bold blue)(%cr, %an)%Creset" --abbrev-commit --all
init.defaultbranch=main`

which just means I can do `git l`

So I just created a pr. I have the same issue:

image

Let's try a squash commit! I looked at the previous network, and I think I was just doing normal commits, not rebase? https://github.com/baltimoreblacktechies/100daysOfCode-2021/network so maybe it will work

**Comment by dmadisetti** [comment]
Dang. I don't think you got credit. Let me revert

**Comment by dmadisetti** [comment]
Wait! You did get the credit: 
image


But only 1 day, and to an aliased user. To fix this, you can set the tracker override: https://github.com/baltimoreblacktechies/100daysOfCode-2022/blob/main/tracker_overrides.json

**Comment by Lito-Frito** [comment]
You are blowing my mind with all this hahaha. But it's also going over my head how I'm not fixing this. Would it be better if I just delete this repo, make a new fork and just reupload the text files? I think the issue stems from the fact that I renamed the folder "Los" to "100DaysofCode_Los" and then tried to merge that change. Not sure how this repo works, but would uploading 5 different days at once count as 5 separate days or just one day

**Comment by Lito-Frito** [comment]
Also, sorry for the hassle. I really wish I was better at git. Still practicing the tutorial you sent

**Comment by dmadisetti** [comment]
It's not a hassle at all !

We could have fixed this a while ago, I just wanted to give you the chance of learning a bit more git
Tracking is based on number of commits founds ([here's the code if you are interested](https://github.com/baltimoreblacktechies/100daysOfCode-2022/blob/main/.code-tracking/cache.py#L41-L52)). Looking back over this, I think I should have been doing normal merges this whole time instead of rebases/ squashes. Sorry about that.

Woops, I should have been more guiding from start. 
I think at this point, reforking is the move- I have definitely had to do that before:

image

**Comment by Lito-Frito** [comment]
Yo that is the realest comic I've ever seen hahaha. And I appreciate all the patience, sincerely. I am learning a lot. 

And interesting. Took a look at the code. One question I had was how the graph traversal algo knows how to tell when something is a new day or not. E.g. if I made a file called Day 5 and a file called Day 6, would the algo count that as two days? Or would it go by the timestamps of the commits?

And sounds good. So I'm clear, basically, refork the project. Reupload the txt files for the days I coded. And then do a PR for that and that should go through?

**Comment by dmadisetti** [comment]
Eh. it's been a second since I wrote it, and it's not well documented- but each commit is counted as a day, there's no time dependence. That's why I was wanting to rebase or squash (cause just merging the branch would have been many commits).

So if you added each file as a different commit, then yes, it would work

**Comment by Lito-Frito** [comment]
Ah gotcha. Ok cool. So I'll delete this repo, fork the BBT 100 Days again, commit each txt file/day as it's own commit, and then submit all of those as a PR, correct? Or do you want me to rebase?

**Comment by dmadisetti** [comment]
We won't have to rebase again- unless there are a ton of commits that don't correspond to days

**Comment by Lito-Frito** [comment]
Ahh gotcha. Ok cool. I'll do that now

**Comment by Lito-Frito** [comment]
Should I wait until the BBT repo deletes the folder with my name before I fork it? Or should I just make a folder with a diff name?

**Comment by dmadisetti** [comment]
Fork, and then delete the folder, not as a separate commit - but lumped in with something so we have the count correct

**Comment by Lito-Frito** [comment]
> Fork, and then delete the folder, not as a separate commit - but lumped in with something so we have the count correct

That makes a lot of sense. Thank you for all the patience and wisdom!

**Comment by Lito-Frito** [comment]
I think I messed up, I'm sorry. I know you said only one commit, but do PRs count as commits too? From the tutorial you sent, it seemed like best practices was to merge branch B into A, then branch A into B to make sure both branches have all the work each individual branch might have. So I did that just to develop good habits. But I think that might mess up the counts now...

**Pull request merged**
